import './styles/main.scss';
import './components/input';
import './components/button';
import './components/select';
import './components/reusable-table';
import './components/employee-card';
import './components/header';
import './components/app-shell';
import './router';
